// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var RList$Rationale = require("rationale/src/RList.js");

function duplicate(param) {
  return List.fold_left((function (acc, x) {
                return /* :: */[
                        x,
                        /* :: */[
                          x,
                          acc
                        ]
                      ];
              }), /* [] */0, param);
}

function initDeck() {
  return duplicate(List.map((function (x) {
                    return /* RegularCard */Block.__(0, [x]);
                  }), RList$Rationale.rangeInt(1)(1, 99)));
}

exports.duplicate = duplicate;
exports.initDeck = initDeck;
/* RList-Rationale Not a pure module */
