// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Cards$ReasonmlTheGame = require("./Cards.bs.js");
var Utils$ReasonmlTheGame = require("./Utils.bs.js");
var Players$ReasonmlTheGame = require("./Players.bs.js");

function init() {
  return /* record */[
          /* players : :: */[
            /* record */[
              /* id */0,
              /* name */Caml_array.caml_array_get(Players$ReasonmlTheGame.player_names, 0),
              /* hand : [] */0
            ],
            /* :: */[
              /* record */[
                /* id */1,
                /* name */Caml_array.caml_array_get(Players$ReasonmlTheGame.player_names, 1),
                /* hand : [] */0
              ],
              /* [] */0
            ]
          ],
          /* deck */Cards$ReasonmlTheGame.initDeck(/* () */0),
          /* stacks : tuple */[
            /* Upwards */Block.__(0, [/* [] */0]),
            /* Upwards */Block.__(0, [/* [] */0]),
            /* Downwards */Block.__(1, [/* [] */0]),
            /* Downwards */Block.__(1, [/* [] */0])
          ]
        ];
}

console.log($$Array.of_list(Utils$ReasonmlTheGame.shuffle(Cards$ReasonmlTheGame.initDeck(/* () */0))));

exports.init = init;
/*  Not a pure module */
