// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var player_names = /* array */[
  "Johanna",
  "Flo",
  "Theresa",
  "Pia",
  "Augustin",
  "Andreas"
];

exports.player_names = player_names;
/* No side effect */
