// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Lens$Rationale = require("rationale/src/Lens.js");

var player_names = /* array */[
  "Johanna",
  "Flo",
  "Theresa",
  "Pia",
  "Augustin",
  "Andreas"
];

var handLens = Lens$Rationale.make((function (x) {
        return x[/* hand */2];
      }), (function (v, a) {
        return /* record */[
                /* id */a[/* id */0],
                /* name */a[/* name */1],
                /* hand */v
              ];
      }));

function gainCards(cards, player) {
  return /* record */[
          /* id */player[/* id */0],
          /* name */player[/* name */1],
          /* hand */List.append(player[/* hand */2], cards)
        ];
}

exports.player_names = player_names;
exports.handLens = handLens;
exports.gainCards = gainCards;
/* handLens Not a pure module */
