// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Random = require("bs-platform/lib/js/random.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function shuffle(xs) {
  var with_random = List.map((function (x) {
          return /* tuple */[
                  Random.bits(/* () */0),
                  x
                ];
        }), xs);
  var sorted = List.sort(Caml_obj.caml_compare, with_random);
  return List.map((function (prim) {
                return prim[1];
              }), sorted);
}

exports.shuffle = shuffle;
/* No side effect */
